import json
import time
import os
from urllib.parse import urlparse
from curl_cffi import requests

# Load Noon cookies from local environment, not source control.
cookies_str = os.getenv("NOON_COOKIE", "")
cookies = {c.split("=")[0]: c.split("=", 1)[1] for c in cookies_str.strip().split("; ") if "=" in c}

headers = {
    "authority": "food.noon.com",
    "accept": "application/json",
    "accept-language": "en-US,en;q=0.9",
    "referer": "https://food.noon.com/",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
}

API_ENDPOINT = "https://food.noon.com/_svc/mp-food-api-mpnoon/consumer/restaurant/outlet/details/guest"

def extract_slug_code(url):
    path_parts = urlparse(url).path.strip("/").split("/")
    outlet_info = path_parts[-1]
    if "-" in outlet_info:
        outlet_code = outlet_info.split("-")[0]
    else:
        outlet_code = outlet_info
    return outlet_code

def scrape_restaurant(url):
    try:
        outlet_code = extract_slug_code(url)
        payload = {
            "countryCode": "ae",
            "outletCode": outlet_code,
            "deliveryAreaCode": None
        }
        resp = requests.post(API_ENDPOINT, json=payload, headers=headers, cookies=cookies, impersonate="chrome")
        data = resp.json()["data"]

        restaurant_name = data.get("name")
        address = data.get("address")
        menu_items = []

        if "menus" in data:
            menu_data = data["menus"][0]["menuData"]
            items_dict = {item["itemCode"]: item for item in menu_data["items"] if item.get("itemType") == "main"}
            for category in menu_data.get("categories", []):
                item_objs = []
                for item_id in category.get("items", []):
                    item = items_dict.get(item_id)
                    if item:
                        item_objs.append({
                            "name": item["name"],
                            "description": item.get("itemDesc", ""),
                            "price": f"AED {item['price']:.2f}"
                        })
                if item_objs:
                    menu_items.append({
                        "category": category["name"],
                        "items": item_objs
                    })
        elif "menu" in data:
            items_dict = {item["itemCode"]: item for item in data["menu"].get("items", []) if item.get("itemType") == "main"}
            categories = data["menu"].get("categories", [])
            for category in categories:
                item_objs = []
                for item_id in category.get("items", []):
                    item = items_dict.get(item_id)
                    if item:
                        item_objs.append({
                            "name": item["name"],
                            "description": item.get("itemDesc", ""),
                            "price": f"AED {item['price']:.2f}"
                        })
                if item_objs:
                    menu_items.append({
                        "category": category["name"],
                        "items": item_objs
                    })

        print(f"âœ… Scraped: {restaurant_name} | Categories: {len(menu_items)}")
        return {
            "restaurant_name": restaurant_name,
            "address": address,
            "url": url,
            "menu": menu_items
        }

    except Exception as e:
        print(f"âŒ Failed: {url} | Reason: {e}")
        return None

def save_json(data, filename):
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def load_json(filename):
    try:
        with open(filename, "r", encoding="utf-8") as f:
            return json.load(f)
    except:
        return []

def main():
    # âœ… Paste your full list of URLs here (up to 500+)
    urls = [
        "https://food.noon.com/outlet/SWTSPCWBCM-Sweet%20&%20Spicy/",
"https://food.noon.com/outlet/BTLKHTALEX-Bait%20El%20Khetyar%20-%20Najda/",
"https://food.noon.com/outlet/SJSKTCB0PD-Sujas%20Kitchen/",
"https://food.noon.com/outlet/RNFGHN5CEH-Ariana%20Afghan/",
"https://food.noon.com/outlet/LYCF3YLTNV-Oly%20Cafe/",
"https://food.noon.com/outlet/TLNPZZL4TM-Italian%20Pizza/",
"https://food.noon.com/outlet/TMHRTNOCNT-Tim%20Hortons/",
"https://food.noon.com/outlet/CNNBN162NK-Cinnabon/",
"https://food.noon.com/outlet/4BTSSHC0ZM-4bites%20Shawarma/",
"https://food.noon.com/outlet/MRHBGVT079-Maraheb/",
"https://food.noon.com/outlet/NDKSTOJQZY-Andoks/",
"https://food.noon.com/outlet/LFRH5887K2-Al%20Farah/",
"https://food.noon.com/outlet/LBZCHCTYIO-Al%20Baz%20Chicken/",
"https://food.noon.com/outlet/MBRBRYDE4P-Ambur%20Dum%20Biryani/",
"https://food.noon.com/outlet/LPZBTCDCEX-Lapaz%20Batchoy/",
"https://food.noon.com/outlet/MLKLTWD352-Malak%20Al%20Tawouk/",
"https://food.noon.com/outlet/SHSTKT0GZC-Shaista%20Gourmet/",
"https://food.noon.com/outlet/DKKGLD0ZEW-Idukki%20Gold/",
"https://food.noon.com/outlet/BRDNDBKNFD-Bread%20and%20Butter/",
"https://food.noon.com/outlet/MRTSNTP1GQ-Emirates%20Net/",
"https://food.noon.com/outlet/VXCNMSLOA3-VOX%20EATS%20Cinema%20Classics%20%E2%80%93%20Popcorn,%20Nachos%20&%20Cinema%20Snacks/",
"https://food.noon.com/outlet/KBBKFTQTJA-Kabab%20&%20Kofta/",
"https://food.noon.com/outlet/LLFRDCH6C2-LuLu%20Fried%20Chicken/",
"https://food.noon.com/outlet/DNKNYVRQDO-Dunkin/",
"https://food.noon.com/outlet/CHWKNGE38J-Chowking/",
"https://food.noon.com/outlet/DTNDCHAJ4K-Diet%20And%20Cheat%20Express/",
"https://food.noon.com/outlet/MCMPRLYRW1-Macao%20Imperial%20Tea/",
"https://food.noon.com/outlet/JLLB8R2M4M-Jollibee/",
"https://food.noon.com/outlet/BBDRNKWTXX-Bubee%20Drinks%20Cafe/",
"https://food.noon.com/outlet/SBWYE089YA-Subway%20-%20Al%20Ain/",
"https://food.noon.com/outlet/SHWRML28UI-Shawarma%20Alagha/",
"https://food.noon.com/outlet/BTLDR1X62R-Bait%20Al%20Deira/",
"https://food.noon.com/outlet/FNLMNDIOU4-Fen%20Al%20Mandi/",
"https://food.noon.com/outlet/PNHSCFUPP0-Open%20House%20Cafe/",
"https://food.noon.com/outlet/CHCKNGCKQB-ChicKing%20-%20Madinat%20Zayed/",
"https://food.noon.com/outlet/LBKR4P8UHK-ALBAIK%20-%20Al%20Ain%20Mall/",
"https://food.noon.com/outlet/PNKBRRG157-Pinkberry%20-%20Al%20Ain%20Mall/",
"https://food.noon.com/outlet/FRSHPLM9RC-%20Kanjikada%20fresh%20palace/",
"https://food.noon.com/outlet/KFC5WM0PRC-KFC/",
"https://food.noon.com/outlet/PRTNFLZBLR-Operation:Falafel/",
"https://food.noon.com/outlet/SFCPLS00I6-SFC%20Plus/",
"https://food.noon.com/outlet/THPZZPLQM4-The%20Pizza%20Pie%20Factory/",
"https://food.noon.com/outlet/RGHTBTNSFV-Right%20Bite/",
"https://food.noon.com/outlet/QSRLSL7NSO-Qasr%20Alasala%20Mandi%20&%20Mathbi/",
"https://food.noon.com/outlet/TYK74A43QX-Taiyaki/",
"https://food.noon.com/outlet/VRTSTNLH9F-Biriyani%20House/",
"https://food.noon.com/outlet/VGCRNR7NJV-Veg%20Corner/",
"https://food.noon.com/outlet/THLLVNK35E-Thalluvandi/",
"https://food.noon.com/outlet/LMBJLKAVNE-Almaabooj%20Alkuwaiti/",
"https://food.noon.com/outlet/TP5RSTZWEK-Top%205%20Restaurant/",
"https://food.noon.com/outlet/MXSRSTPG31-Max's/",
"https://food.noon.com/outlet/LBKLWHH0M8-ALBAIK%20-%20Al%20Wahda%20Mall/",
"https://food.noon.com/outlet/CHTM4MEPWI-Chatime/",
"https://food.noon.com/outlet/ZTRWZTOK8L-Zaatar%20w%20Zeit/",
"https://food.noon.com/outlet/RTJ3V7TITU-Ritaj/",
"https://food.noon.com/outlet/NRSWHNL6X9-Al%20Noor%20Modern%20Bakery/",
"https://food.noon.com/outlet/HSFTCFK0OX-House%20of%20Tea%20Cafe/",
"https://food.noon.com/outlet/MCDNLDNZ63-McDonald's/",
"https://food.noon.com/outlet/HRDSOIWXIO-Hardee's/",
"https://food.noon.com/outlet/NTHWDL9JQ9-On%20The%20Wood/",
"https://food.noon.com/outlet/HMCRTCR382-Homecourt%20Cafe/",
"https://food.noon.com/outlet/LFRHGRPONL-Al%20Farah%20Gourmet/",
"https://food.noon.com/outlet/RDLSHWM0QX-Ared%20Al%20Shawarma/",
"https://food.noon.com/outlet/RLNSRSPPZQ-Kahani/",
"https://food.noon.com/outlet/LLBRT9J82O-Allo%20Beirut/",
"https://food.noon.com/outlet/NQLNRSNW6B-UNIQUE%20AL%20AIN/",
"https://food.noon.com/outlet/KMTBTPZRCN-Kamat/",
"https://food.noon.com/outlet/SNGMFQ700X-Sangam/",
"https://food.noon.com/outlet/DPJYTN4VC3-Deepjyoti%20nepali%20resturant/",
"https://food.noon.com/outlet/THNSLMJMFV-EAThans%20Lomi/",
"https://food.noon.com/outlet/NJDPLCI7RS-Najd%20Palace/",
"https://food.noon.com/outlet/KTTNDN2UNW-Kuttanadan%20Grills/",
"https://food.noon.com/outlet/CHNCHNIBIU-Chin%20Chin%20-%20Chinese,%20Asian%20&%20Noodles/",
"https://food.noon.com/outlet/CLCTLNWDRN-Calicut%20Lounge/",
"https://food.noon.com/outlet/BWRCHCZ4R2-Mannat%20Hyderabad/",
"https://food.noon.com/outlet/KSHRYLGGK4-Koshary%20El%20Sayed%20Hanfy/",
"https://food.noon.com/outlet/MRRYBRBNAW-Marrybrown/",
"https://food.noon.com/outlet/BLBN5Y2P3I-B.%20Laban",
"https://food.noon.com/outlet/SSHLLC44OH-Seashell/",
"https://food.noon.com/outlet/BKNRVLFC2S-Bikanervala/",
"https://food.noon.com/outlet/BTLKHTALEX-Bait%20El%20Khetyar%20-%20Najda/",
"https://food.noon.com/outlet/RYLPNYQXHQ-Royal%20Pinoy/",
"https://food.noon.com/outlet/QSRLZZR6QJ-Qasar%20Al%20Izz%20Mandi/",
"https://food.noon.com/outlet/SRYHLBIMYN-Saraya%20Halab/",
"https://food.noon.com/outlet/VRTSTR2II5-Ever%20Taste/",
"https://food.noon.com/outlet/TKKTNGHWJN-Tikka%20Tonight/",
"https://food.noon.com/outlet/LJWDZ10011-Al%20Ajaweed/",
"https://food.noon.com/outlet/ZNZNTRZBCQ-Zanzan%20-%20Eat/",
"https://food.noon.com/outlet/CRSPYCC0JP-Crispy%20Chicken/",
"https://food.noon.com/outlet/SNGTHV20QP-Sangeetha%20Vegetarian/",
"https://food.noon.com/outlet/BRCYT45KXQ-Boracay/",
"https://food.noon.com/outlet/LHRLSHZOM9-Al%20Hara%20Al%20Shamia/",
"https://food.noon.com/outlet/PZZHTI1EIG-Pizza%20Hut/",
"https://food.noon.com/outlet/DBHYDR1B77-Aadaab%20Hyderabad/",
"https://food.noon.com/outlet/FLFLTSYHFH-Foul%20w%20Falafel/",
"https://food.noon.com/outlet/PYYNNRIHMD-Payyannur%20-%20Madinat%20Zayed%20Mall/",
"https://food.noon.com/outlet/SMRNKRNBJK-Simran%20Ki%20Rasoi%20Kitchen/",
"https://food.noon.com/outlet/PRSKTCI5JP-Paris%20Kitchen/",
"https://food.noon.com/outlet/NDNBYNJU4D-Indian%20By%20Nature/",
"https://food.noon.com/outlet/DSKRSTU4X4-Daska/",
"https://food.noon.com/outlet/WHTPRGBC3T-White%20Paragon/",
"https://food.noon.com/outlet/BRYNBRUT62-Biriyani%20Brothers/",
"https://food.noon.com/outlet/BDLZZR55SD-Abdul%20Aziz/",
"https://food.noon.com/outlet/JBBRBHW98Y-Jabbar%20Bhai%20Biriyani/",
"https://food.noon.com/outlet/GZBJVDSTXJ-Gazebo/",
"https://food.noon.com/outlet/GDRSTR67H5-Gad/",
"https://food.noon.com/outlet/CHCBYNLUM4-Chic%20Boy%20Inasal/",
"https://food.noon.com/outlet/GRNDTH3IX4-Grand%20Thai/",
"https://food.noon.com/outlet/LSLHNJ202R-Alsalehany%20Cafeteria%20and%20Grills/",
"https://food.noon.com/outlet/LBKHMDMPYQ-ALBAIK%20-%20Hamdan%20Street/",
"https://food.noon.com/outlet/NCLSHWPYPL-Uncle%20Shawerma/",
"https://food.noon.com/outlet/LFRJFRZCZZ-Al%20Farooj%20Fresh/",
"https://food.noon.com/outlet/MMBCHTEGA9-Mumbai%20Chat%20and%20Restaurant/",
"https://food.noon.com/outlet/CLCTFDSLEJ-Calicut%20Foodies%20Express/",
"https://food.noon.com/outlet/FSNMRV1QKK-Godavari%20Ruchulu/",
"https://food.noon.com/outlet/TYYBHYNYLQ-TAYYAB%20HYDERABAD/",
"https://food.noon.com/outlet/SWDSVGPKWF-Swades%20Vegetarian/",
"https://food.noon.com/outlet/CHHPPN4SS7-Chhappan%20Bhog/",
"https://food.noon.com/outlet/PRNMLTO1EN-Puranmal/",
"https://food.noon.com/outlet/PPMRPHHV08-Papa%20Murphy's%20Pizza/",
"https://food.noon.com/outlet/STRZBGCRBY-Star%20Uzbegim/",
"https://food.noon.com/outlet/BSKNRB2632-Baskin%20Robbins/",
"https://food.noon.com/outlet/VSHLSBZGHB-Vaishali's%20Bombay%20Bites/",
"https://food.noon.com/outlet/SBWY4J10LL-Subway%20-%20Dubai%20Silicon%20Oasis/",
"https://food.noon.com/outlet/SLMNMSDBNV-Salaam%20Namaste/",
"https://food.noon.com/outlet/PRPNJBJXVL-Pure%20Punjabi/",
"https://food.noon.com/outlet/CHTBZRIRGJ-Chaat%20Bazaar/",
"https://food.noon.com/outlet/MCDNLDEK8G-McDonald's%20in%2015%20minutes/",
"https://food.noon.com/outlet/LPZBTCHZSF-Lapaz%20Batchoy%20(Dubai%20Marina)/",
"https://food.noon.com/outlet/LFRNWE23FU-il%20Forno/",
"https://food.noon.com/outlet/BCLDNSCSGN-Bacolod%20Inasal%20BBQ/",
"https://food.noon.com/outlet/MYGVNDN6CN-My%20Govinda's/",
"https://food.noon.com/outlet/DLYMLSQ1MZ-Daily%20Meals%20Co/",
"https://food.noon.com/outlet/PPJHNS609S-Papa%20Johns%20Pizza/",
"https://food.noon.com/outlet/WSNFDHT8P2-We%20Asian%20Food%20Hall/",
"https://food.noon.com/outlet/DMNSS3QSN6-Domino's/",
"https://food.noon.com/outlet/BZKFRDJS78-Bazooka%20Fried%20Chicken/",
"https://food.noon.com/outlet/RBNTDKCQKV-Urban%20Tadka/",
"https://food.noon.com/outlet/KLCHKNPK5A-Kulcha%20King%20Indian/",
"https://food.noon.com/outlet/KTRNSWATIW-Katrina%20Sweets%20&%20Confectionery/",
"https://food.noon.com/outlet/LFFHPAKBOA-Laffah/",
"https://food.noon.com/outlet/WDRNG5Q49U-Wide%20Range/",
"https://food.noon.com/outlet/CPPRKT9T6M-Copper%20Kettle/",
"https://food.noon.com/outlet/HZRTBLMAF0-Hazart%20Bilal%20Afgani/",
"https://food.noon.com/outlet/TSTFLHXHJG-Taste%20of%20Lahore%20Baithak/",
"https://food.noon.com/outlet/PPPRLNFTMY-Pepper%20Lane/",
"https://food.noon.com/outlet/NJPPRHGQMW-Anjappar/",
"https://food.noon.com/outlet/ZRFSHN6DHC-Zarafshon/",
"https://food.noon.com/outlet/CHCKNGE6T5-Chicking/",
"https://food.noon.com/outlet/DSKNGM1WFK-Dosa%20King/",
"https://food.noon.com/outlet/SSHD5XS1A0-SushiDo/",
"https://food.noon.com/outlet/SBWY5BPXCY-Subway%20-%20Jumeirah%20Park/",
"https://food.noon.com/outlet/FGHNPL0NTA-Afghan%20Palace/",
"https://food.noon.com/outlet/NJPPRGZ909-Anjappar%20-%20DSO/",
"https://food.noon.com/outlet/HLLSHWEG2B-Halla%20Shawarma/",
"https://food.noon.com/outlet/FLFLLR1NWX-Falafil%20Al%20Rabiah%20Al%20Khadhra/",
"https://food.noon.com/outlet/FLL2Y2WZZY-FiLLi/",
"https://food.noon.com/outlet/HRPRSD6D9D-Hari%20Prasad%20Pure%20Vegetarian/",
"https://food.noon.com/outlet/DSRCBWWF8W-Desi%20Rice%20Bowl/",
"https://food.noon.com/outlet/CHCKNGYY4K-ChicKing%20-%20Dubai%20Silicon%20Oasis/",
"https://food.noon.com/outlet/JJCHCKFKYB-JJ%20Chicken/",
"https://food.noon.com/outlet/CPGHQIB809-Coop/",
"https://food.noon.com/outlet/PPYS3SPQ3U-Popeyes/",
"https://food.noon.com/outlet/DRJLNGCM1O-Darjeeling%20Cafe/",
"https://food.noon.com/outlet/GRLLCRI9XG-Grill%20Corner%20-%20Pinoy%20Favorites/",
"https://food.noon.com/outlet/DLYRST08TA-Daily%20Express%20-%20Dubai%20Silicon%20Oasis/",
"https://food.noon.com/outlet/SPCHVN1WMD-Spice%20Haven/",
"https://food.noon.com/outlet/MLGD5SYJGP-Malgudi/",
"https://food.noon.com/outlet/PRTHKNHK72-Paratha%20King/",
"https://food.noon.com/outlet/PKBL0SO3YL-Poke%20Bol/",
"https://food.noon.com/outlet/LMRRSTO1WE-Al%20Amoor/",
"https://food.noon.com/outlet/WNGSTPEYX9-Wingstop/",
"https://food.noon.com/outlet/RJMLTE6V42-Raju%20Omlet/",
"https://food.noon.com/outlet/BRWNPNNOCB-Brownie%20Point/",
"https://food.noon.com/outlet/HYDRBDKEQH-Hyderabad%20Fusion/",
"https://food.noon.com/outlet/FTYRNDM3UV-Fatayer%20And%20Koshary%20Al%20Basha/",
"https://food.noon.com/outlet/BRYNWLP599-Biryaniwalla%20and%20Co./",
"https://food.noon.com/outlet/HNSTBWKYJM-Honest%20Bowl/",
"https://food.noon.com/outlet/KCLGL1HHI3-Kcal%20%E2%80%93%20The%20Original%20Healthy/",
"https://food.noon.com/outlet/SGRRTNHBE2-Sagar%20Ratna/",
"https://food.noon.com/outlet/FNPCKS07FO-FNP%20Cakes/",
"https://food.noon.com/outlet/VSNTBH4SEA-Vasanta%20Bhavan%20-%20Discovery%20Gardens/",
"https://food.noon.com/outlet/MMSREYA9G6-Amma's/",
"https://food.noon.com/outlet/SHWRMHPR60-Shawarma%20Houzz%20Shawarma%20&%20Grills%20&%20Broasted/",
"https://food.noon.com/outlet/PKDRBR3TA0-Pak%20Darbar/",
"https://food.noon.com/outlet/HYDRBDOC00-Hyderabad%20Se/",
"https://food.noon.com/outlet/SLRDD4DI53-SEA%20LORD/",
"https://food.noon.com/outlet/MMB4IP9QAE-Umami/",
"https://food.noon.com/outlet/LFRHEWROYK-Al%20Farah/",
"https://food.noon.com/outlet/ZRBKTPZTZH-Zaroob%20%E2%80%93%20Levant%20Street%20Flavors/",
"https://food.noon.com/outlet/GLRSTRPG7W-Eagle%20Restaurant/",
"https://food.noon.com/outlet/LMRXPRDKSL-Al%20Amoor%20Express/",
"https://food.noon.com/outlet/NWMRNDYUTD-New%20Marina/",
"https://food.noon.com/outlet/LBKLRSVVBZ-ALBAIK%20-%20Al%20Rashidiya/",
"https://food.noon.com/outlet/GRNDMHI0MC-Grand%20Mehfil/",
"https://food.noon.com/outlet/KSNCNDRKNM-Lola%20Lita%20-%20Filipino%20Comfort%20Food/",
"https://food.noon.com/outlet/WDDNC3VZ1T-Wadi%20Doan/",
"https://food.noon.com/outlet/LYLLPR9FJI-Lyallpur/",
"https://food.noon.com/outlet/NYBHNDJPNU-Nayaab%20Haandi/",
"https://food.noon.com/outlet/PKLYRJQR09-Pak%20Liyari/",
"https://food.noon.com/outlet/DRLZMNZ6JJ-Dar%20Al%20Zaman%20Tunisia/",
"https://food.noon.com/outlet/NWKZHK0482-Kozhikode%20Star/",
"https://food.noon.com/outlet/KRV535Z0ST-Krave/",
"https://food.noon.com/outlet/KRSPYK82SH-Krispy%20Kreme/",
"https://food.noon.com/outlet/TMPLNGD17A-Timplang%20Ala%20Eh/",
"https://food.noon.com/outlet/MSTRPZU1V1-Maestro%20Pizza/",
"https://food.noon.com/outlet/PNDCHNY37F-Panda%20Chinese/",
"https://food.noon.com/outlet/CHCHCXU8AV-Chicha%20Bakehouse/",
"https://food.noon.com/outlet/PKZMRSH3LB-Pak%20Azam/",
"https://food.noon.com/outlet/STRBCKV8ZC-Starbucks/",
"https://food.noon.com/outlet/DRGNHS6ZDG-Dragon%20House/",
"https://food.noon.com/outlet/ZMZMMNKHOF-Zam%20Zam%20Mandi/",
"https://food.noon.com/outlet/THNTCN9M25-Authentic%20Angels%20Bisaya/",
"https://food.noon.com/outlet/SRVNBHJRW5-Saravanaa%20Bhavan/",
"https://food.noon.com/outlet/BMBYBSM9A8-Bombay%20Basera%20-%20Business%20Bay/",
"https://food.noon.com/outlet/SRSWRYI516-Sri%20Aiswariya%20Vegetarian/",
"https://food.noon.com/outlet/SLKRRSOG8O-Salkara%20-%20Dubai%20Media%20City/",
"https://food.noon.com/outlet/CHTBZRLE4D-Chaat%20Bazaar%20-%20Al%20Nahda/",
"https://food.noon.com/outlet/LCTHTLDYV0-Luca%20%E2%80%93%20Italian%20Pasta/",
"https://food.noon.com/outlet/MRTSSR9TW7-Emirates%20Sea/",
"https://food.noon.com/outlet/LBKLNHLRU6-ALBAIK%20-%20Al%20Nahda/",
"https://food.noon.com/outlet/CHCLL28GUQ-Chocolala/",
"https://food.noon.com/outlet/DLYRSTV6JN-Daily%20Express%20-%20Deira%20City%20Center/",
"https://food.noon.com/outlet/KKHLSHX2E3-Koukh%20Al%20Shay/",
"https://food.noon.com/outlet/NHDMNDM3AV-Nahdi%20Mandi/",
"https://food.noon.com/outlet/PRNMLLU55V-Puranmal%20Al%20Quoz/",
"https://food.noon.com/outlet/STDNTBHRAX-Student%20Biryani%20-%20Al%20Barsha/",
"https://food.noon.com/outlet/TYBFLFHWZY-Atyab%20Falafel/",
"https://food.noon.com/outlet/SSHZNA6VXE-Sushi%20Zen%20-%20JLT/",
"https://food.noon.com/outlet/CRCMJAIBHK-Curcum/",
"https://food.noon.com/outlet/RGHTBTFK8A-Right%20Bite%20Express/",
"https://food.noon.com/outlet/SBWY3GYUX5-Subway-Bur%20Dubai,Al%20Mankhool/",
"https://food.noon.com/outlet/TCSNDBO59X-Tacos%20and%20Burritos/",
"https://food.noon.com/outlet/SBWY3YXF8I-Subway-Al%20Safa%20ENOC/",
"https://food.noon.com/outlet/MRTSRRTBNF-Amritsr/",
"https://food.noon.com/outlet/SLKRRSGMC0-Salkara%20-%20Al%20Qusais/",
"https://food.noon.com/outlet/SHWRMPDJPM-Shawarma%20Prince/",
"https://food.noon.com/outlet/MHRJBH76AU-Maharaja%20Bhog/",
"https://food.noon.com/outlet/GRNDHYQL7X-Grand%20Hyderabad/",
"https://food.noon.com/outlet/RSSLLDERWF-Russell%20Dave%20Bakery/",
"https://food.noon.com/outlet/SFRSTRRCF4-SAIF/",
"https://food.noon.com/outlet/ZTTSKRARFK-Zutto%20Suki%20Ramen/",
"https://food.noon.com/outlet/KNJKDTDNX7-Kanjikada/",
"https://food.noon.com/outlet/TH500CT3YY-The%20500%20Calorie%20Project%20-Business%20Bay/",
"https://food.noon.com/outlet/PTFRPZ2OAM-Pitfire%20Pizza/",
"https://food.noon.com/outlet/BRDBKN72FF-Bur%20Dubai%20Kandy%20SriLankan/",
"https://food.noon.com/outlet/BRBRONSK8S-Barbar/",
"https://food.noon.com/outlet/DNNYSVL3BM-Denny's/",
"https://food.noon.com/outlet/SHKYSPWS22-Shakey's%20Pizza%20Parlor/",
"https://food.noon.com/outlet/THTMMY7M2B-Tummy%20Tales/",
"https://food.noon.com/outlet/BMBYBSQ22W-Bombay%20Basera%20-%20Mankhool/",
"https://food.noon.com/outlet/CHKYCH4OTV-Chickville/",
"https://food.noon.com/outlet/CTTCFFRV2H-Cotti%20Coffee/",
"https://food.noon.com/outlet/SHRFBHZI8W-Sharief%20Bhai%20Biryani/",
"https://food.noon.com/outlet/THNHC2BUBJ-Tahinah/",
"https://food.noon.com/outlet/HMDNR6IH40-Home%20Diner/",
"https://food.noon.com/outlet/RSMBYVOY5Y-Rasam%20By%20Avinash%20Mohan/",
"https://food.noon.com/outlet/SRMRVTOZPY-Sree%20Amaravathi/",
"https://food.noon.com/outlet/SPCSLH035O-Spice%20Isle/",
"https://food.noon.com/outlet/WRSNMNOYQ1-Warsan%20Mandi/",
"https://food.noon.com/outlet/KBBQRSJFWS-Kabab%20Queue%20-%20Persian%20Kebab%20BBQ%20&%20Iranian%20Grill/",
"https://food.noon.com/outlet/CLCTPR6CVG-Calicut%20Paragon/",
"https://food.noon.com/outlet/BBGHNJGXLK-Baba%20Ghanouj/",
"https://food.noon.com/outlet/TSTFML3IP7-Taste%20of%20Malabar/",
"https://food.noon.com/outlet/DLYRSTX97G-Daily%20Express-%20Al%20Barsha/",
"https://food.noon.com/outlet/PFCHNGO5RD-P.F.%20Chang's",
"https://food.noon.com/outlet/QSRLSBV6UZ-Qasr%20Sabaa/",
"https://food.noon.com/outlet/BRYNWLA29I-Biryaniwalla%20&%20Co/",
"https://food.noon.com/outlet/KYCHNYFA7Y-KyoChon/",
"https://food.noon.com/outlet/FFRDBWHGU8-Affordabowls%20-%20Rice%20Bowls%20&%20Mashed%20Potato%20Bowls/",
"https://food.noon.com/outlet/KDYLL3P4CH-Kodiyal/",
"https://food.noon.com/outlet/BTLSHYBHE6-Bait%20Al%20Shay%20Alaseel%20Cafeteria/",
"https://food.noon.com/outlet/GRNDSWPL9O-Grand%20Swathi/",
"https://food.noon.com/outlet/SLTBSNM383-SALATA/",
"https://food.noon.com/outlet/SLTNLRXVEG-Sultan%20Al%20Arab/",
"https://food.noon.com/outlet/TMSHRSUDKW-Tamasha/",
"https://food.noon.com/outlet/MZMRSTHKAK-Maazim/",
"https://food.noon.com/outlet/TYBKTCV79O-Tayeb%20Kitchen/",
"https://food.noon.com/outlet/MHFLBRWFR5-Mehfil%20Biryani/",
"https://food.noon.com/outlet/RTFDM5SE2R-Art%20Of%20Dum/",
"https://food.noon.com/outlet/LTKHS367Z4-Latakia%20House/",
"https://food.noon.com/outlet/DNRDLOQ0S0-Doner%20Deli/",
"https://food.noon.com/outlet/CLCFF2YL6I-Colo%20Coffee/",
"https://food.noon.com/outlet/HTPLTFR0AQ-Hot%20Plate/",
"https://food.noon.com/outlet/CHTBZR5J60-Chaat%20Bazaar%20-%20Barsha/",
"https://food.noon.com/outlet/DLCHWLYTAS-Daal%20Chawal/",
"https://food.noon.com/outlet/LBKLBROCKE-ALBAIK%20-%20Al%20Barsha/",
"https://food.noon.com/outlet/SBWY407OA2-Subway%20-%20Dubai%20Festival%20City/",
"https://food.noon.com/outlet/HTBNSLQA2Z-HOTBUN%20Sliders/",
"https://food.noon.com/outlet/RMNHYD6JTZ-Rumaan%20Hyderabad/",
"https://food.noon.com/outlet/TJNLSTYXFI-Tajen%20Alsit/",
"https://food.noon.com/outlet/BNNBFNU34I-Bannu%20Beef%20Nalli%20Pulao/",
"https://food.noon.com/outlet/SBWYRA8CS5-Subway-Al%20Rigga/",
"https://food.noon.com/outlet/CRSPYCNCGP-Crispy%20Chicky/",
"https://food.noon.com/outlet/WYBCKBJ5XM-Wayback%20Burgers/",
"https://food.noon.com/outlet/RWBLSHPSHV-Rawabi%20Al%20Sham/",
"https://food.noon.com/outlet/NLFRHYPD1X-Niloufer%20Hyderabad/",
"https://food.noon.com/outlet/LBKLKRNIZB-ALBAIK%20-%20Al%20Karama/",
"https://food.noon.com/outlet/MNSHSK2JWV-Manisha's%20Kitchen/",
"https://food.noon.com/outlet/CHWLCHZEAP-Chawal%20&%20Chapati/",
"https://food.noon.com/outlet/TRTLL9JV1D-Tortilla/",
"https://food.noon.com/outlet/MMXRST4O7P-Miamix/",
"https://food.noon.com/outlet/CHNCHNQRI1-Chin%20Chin/",
"https://food.noon.com/outlet/DLHDRBP57A-Delhi%20Darbar/",
"https://food.noon.com/outlet/MSTRDRJ4BL-Mustard/",
"https://food.noon.com/outlet/DBNRSPDJCV-Debonairs%20Pizza/",
"https://food.noon.com/outlet/KSTRBHGO6M-Kasturi%20Bhavan/",
"https://food.noon.com/outlet/CCSNS77HFV-Occasions/",
"https://food.noon.com/outlet/BHBCKTDG6F-Bhai%20Bucket%20Biryani/",
"https://food.noon.com/outlet/LBDLLHLNYP-Al%20Abdallah/",
"https://food.noon.com/outlet/SYNMNDK2JP-Seiyun%20Mandi/",
"https://food.noon.com/outlet/VKSNRSS182-Vkusno%20Russian%20Kitchen/",
"https://food.noon.com/outlet/MXNMTCHEUE-Mix%20'N'%20Match/",
"https://food.noon.com/outlet/JRFLL4XX86-Jarful/",
"https://food.noon.com/outlet/SNLTSO3VAZ-Asian%20Lotus/",
"https://food.noon.com/outlet/RMMSO2II8N-Aaraamam/",
"https://food.noon.com/outlet/DLKDRSE1AQ-Idli%20Kadai/",
"https://food.noon.com/outlet/LBKLGHITM3-ALBAIK%20-%20Al%20Ghurair/",
"https://food.noon.com/outlet/NDR50034QI-Under500%20-%20Healthy,%20Bowls%20and%20Salads/",
"https://food.noon.com/outlet/KRCHDRRGD7-Karachi%20Darbar/",
"https://food.noon.com/outlet/BLBN9YJWK9-B%20Laban/",
"https://food.noon.com/outlet/THKKLMNQ4N-Thakkolam/",
"https://food.noon.com/outlet/MGHNFDB0MC-Meghana%20Foods/",
"https://food.noon.com/outlet/BNGLRN6ES0-Bengaluru%20Naati%20Mane/",
"https://food.noon.com/outlet/CRRYCH4QQ3-Curry%20Chatti%20-Al%20Qusais/",
"https://food.noon.com/outlet/PNJBDHJR5H-Punjabi%20Dhaba%20-%20Business%20Bay/",
"https://food.noon.com/outlet/PSHKNRLQVG-Pushkin%20Russian/",
"https://food.noon.com/outlet/MMSLLMI8PL-Mami's%20Illam%20Pure%20Veg/",
"https://food.noon.com/outlet/LMDHRSGSJ1-Al%20Aumdah/",
"https://food.noon.com/outlet/TPSTDA0UCY-Tea%20Post/",
"https://food.noon.com/outlet/FRJLBDH8L5-Farooj%20Al%20Abdalla/",
"https://food.noon.com/outlet/CLCTNTWSKK-Calicut%20Notebook/",
"https://food.noon.com/outlet/LBKSTWWFPC-ALBAIK%20-%20Satwa/",
"https://food.noon.com/outlet/SLGXPRCRNT-Silog%20Express/",
"https://food.noon.com/outlet/RMNHYDH9AN-Rumaan%20Hyderabad%20-%20Al%20Karama/",
"https://food.noon.com/outlet/MNDRNKSC65-Mandarin%20Oak%20-%20Chinese,%20Asian%20&%20More-%20Business%20Bay/",
"https://food.noon.com/outlet/CTYFJYXCWK-City%20Of%20Joy/",
"https://food.noon.com/outlet/RDMMNMGSPK-Erodu%20Amman%20Mess/",
"https://food.noon.com/outlet/CNNMNTCYIK-Cinnamon%20Tree/",
"https://food.noon.com/outlet/SRBLJB0Y2Y-Sri%20Balaji%20Bhavan/",
"https://food.noon.com/outlet/GRZLSC7N60-Grizlis%20Creperie%20&%20Swirls/",
"https://food.noon.com/outlet/CCNCPT4CF1-Acai%20Concept/",
"https://food.noon.com/outlet/SBWY4TJ1O4-Subway%20-%20Nadd%20Al%20Hamar/",
"https://food.noon.com/outlet/BYTKBKTF0C-Baytak%20Bakery/",
"https://food.noon.com/outlet/RLYRST3R7E-Araliya%20Lanka/",
"https://food.noon.com/outlet/HTCST0OCIC-Oh%20Tacos/",
"https://food.noon.com/outlet/DNDGLTEOL8-Dindigul%20Thalappakatti%20Biriyani/",
"https://food.noon.com/outlet/YRSQGMLL86-Iyer's%20Premium%20Veg/",
"https://food.noon.com/outlet/SSBCKTJBHT-SS%20Bucket%20Biryani/",
"https://food.noon.com/outlet/GMNXPR4VVB-Agemono%20Express/",
"https://food.noon.com/outlet/LFKHRMCB72-Al%20Fakher%20Mandi%20&%20Traditional%20Food/",
"https://food.noon.com/outlet/CFFBNOPF5E-Caffe%CC%81%20Buono/",
"https://food.noon.com/outlet/JWHRTL31TN-Jawharat%20Al%20Sham/",
"https://food.noon.com/outlet/MRTHSLVGN1-Amrutha/",
"https://food.noon.com/outlet/ZKRYTLUZJ8-Zekrayat%20Al%20Sham/",
"https://food.noon.com/outlet/WMRTHZTKU6-Wemart/",
"https://food.noon.com/outlet/SHRLMDN5C4-Sheraa%20Al%20Madena%20Kitchen/",
"https://food.noon.com/outlet/THSYTRJYHR-The%20Easy%20Eatery%20-%20Pizzas,%20Pastas,%20Chinese%20&%20Rice%20Bowls/",
"https://food.noon.com/outlet/GDNSSBYWS8-Goodness%20Bowl/",
"https://food.noon.com/outlet/SBWYBI3FNO-Subway-Business%20Bay/",
"https://food.noon.com/outlet/DYRLSHY0RC-Dyar%20Al%20Sham/",
"https://food.noon.com/outlet/PNDCBK310B-Pandecia%20Bakery%20Cafe/",
"https://food.noon.com/outlet/CHCKCNGX18-Chick%20Central/",
"https://food.noon.com/outlet/TGRSGR31I1-Tiger%20Sugar/",
"https://food.noon.com/outlet/QDRHMNQO6Q-Qedreh%20w%20Mansaf/",
"https://food.noon.com/outlet/KHLDSBRWHR-Khalids%20Biryani/",
"https://food.noon.com/outlet/TH500CLMHG-The%20500%20Calorie%20Project%20-%20Muwailah/",
"https://food.noon.com/outlet/TTLLYH1EM4-Totally%20Healthy/",
"https://food.noon.com/outlet/LSHYLK7U4Q-Al%20Shai%20Al%20Kashmiri/",
"https://food.noon.com/outlet/DFSHSFGWGK-De%20Fish%20Seafood/",
"https://food.noon.com/outlet/QSRSLKI4VN-Qaser%20Sialkot%20Cafe%20&%20Sweets/",
"https://food.noon.com/outlet/CRRYCH8OAP-Curry%20Chatti-%20Muweilah%20Commercial/",
"https://food.noon.com/outlet/STDXPR8P67-Ustad%20Hotel/",
"https://food.noon.com/outlet/SBWYK674P4-Subway%20-%20Muweilah%20Commercial%20NEST%20AL%20JADA/",
"https://food.noon.com/outlet/M10RST37MF-M10%20Resto/",
"https://food.noon.com/outlet/LBTLNJZOE0-Al%20Bait%20Al%20Najdi%20-%20Mandi%20&%20Madbhi/",
"https://food.noon.com/outlet/QSRLTMZLVI-Qasr%20AlTaemiah/",
"https://food.noon.com/outlet/MNRTMW3UYS-Manarat/",
"https://food.noon.com/outlet/NZMTHYSAB4-Nizamat%20Hyderabad/",
"https://food.noon.com/outlet/PNRRSTU49V-Panoor%20-%20Sharjah/",
"https://food.noon.com/outlet/LBKLZHHNUQ-ALBAIK%20-%20Al%20Zahia%20Mall%20Sharjah/",
"https://food.noon.com/outlet/LKLHSQ2PDO-Al%20Kalha/",
"https://food.noon.com/outlet/RYSGRMOKTQ-Aryaas%20Gourmet%20Veg/",
"https://food.noon.com/outlet/TMLNDRJ70M-Tamil%20Nadu%20Restaurant/",
"https://food.noon.com/outlet/HTFFNCQEQW-HOTiffin/",
"https://food.noon.com/outlet/MMCHDDPCNS-Ummachide%20Adukala/",
"https://food.noon.com/outlet/CRBCFFLQAS-Caribou%20Coffee/",
"https://food.noon.com/outlet/CHCKNGDUDK-ChicKing%20-%20City%20Centre%20Al%20Zahia/",
"https://food.noon.com/outlet/SSHNWYPBSK-Sushi%20Now/",
"https://food.noon.com/outlet/FDBKWVSJB1-Foodbook/",
"https://food.noon.com/outlet/BRYNKBP7WZ-Biryani%20Kabab/",
"https://food.noon.com/outlet/LJLSFR5SJ2-Al%20Jalsa%20For%20Mandi/",
"https://food.noon.com/outlet/BRGR28TH76-Burger28/",
"https://food.noon.com/outlet/LTSZNG6MPI-Let's%20Zinger/",
"https://food.noon.com/outlet/JNNCFTZXOY-Jenan%20Cafeteria/",
"https://food.noon.com/outlet/BHRZBR3MTC-Behrouz%20Biryani%20-%20Muwailih%20Commercial/",
"https://food.noon.com/outlet/CHNNBCZJIM-Chennai%20Bucket%20Biryani/",
"https://food.noon.com/outlet/CHNDNCJLZ3-Chandni%20Chowk%20Vegetarian/",
"https://food.noon.com/outlet/THLSSRW7J1-Thalassery/",
"https://food.noon.com/outlet/SSYPRVURVS-Sasya%20Pure%20Veg/",
"https://food.noon.com/outlet/THCFFL518X-The%20Coffee%20Lab/",
"https://food.noon.com/outlet/DNCSSC3138-ADNOC%20Oasis%20Cafe/",
"https://food.noon.com/outlet/PL3V2YIUX9-PAUL%20Bakery/",
"https://food.noon.com/outlet/SHMSNBB4KZ-Shamseen%20Bakeries%20(Broasted%20&%20Shawarma)/",
"https://food.noon.com/outlet/PNSRMNCXKD-Pinsa%20Romana%20-%20Etihad%20Plaza/",
"https://food.noon.com/outlet/MSLSTRDPT4-Masala%20Street/",
"https://food.noon.com/outlet/ZYMRNDXKC0-Cakes%20By%20Zoya%20(Zoya%20Umran%20Desserts)/",
"https://food.noon.com/outlet/KRKWSMMNNY-Karak%20W%20Samboosa/",
"https://food.noon.com/outlet/PNKBRRFR2H-Pinkberry/",
"https://food.noon.com/outlet/GNGRLM24WY-Ginger%20&%20Lemon%20Kerala/",
"https://food.noon.com/outlet/MNSHSTQ0QQ-Manoushe%20Street/",
"https://food.noon.com/outlet/MZNFSHQ5RR-Amazon%20Fish/",
"https://food.noon.com/outlet/BLBNDR4S94-Blaban%20Dairy/",
"https://food.noon.com/outlet/BMBYCN367T-Bombay%20Canteen/",
"https://food.noon.com/outlet/SPCPWD86M0-Soup%20Cup/",
"https://food.noon.com/outlet/DL21FO77RV-Deli%2021/",
"https://food.noon.com/outlet/NDRNG1TZ6P-Naderang/",
"https://food.noon.com/outlet/GNGTRCH4K1-Gangotri%20Cafeteria/",
"https://food.noon.com/outlet/BFFLWLS8EI-Buffalo%20Wild%20Wings/",
"https://food.noon.com/outlet/LKHWBRJULV-Al%20Khawabi/",
"https://food.noon.com/outlet/HWYNTR68GJ-Hawyna%20Traditional%20Food/",
"https://food.noon.com/outlet/BRYNPTCVEM-Biryani%20Pot%20-%20Savour%20The%20Heritage/",
"https://food.noon.com/outlet/MMSPSTSNUQ-Mama%60s%20Pasta%20By%20Wedallas/",
"https://food.noon.com/outlet/CHCKSFN9QY-Chickees%20Fried%20Chicken/",
"https://food.noon.com/outlet/THMCKTSWXF-The%20Mac%20Kitchen/",
"https://food.noon.com/outlet/FLLL5F87G2-FilLLi/",
"https://food.noon.com/outlet/PLSTNC1S41-Opal%20Stone%20Cafe/",
"https://food.noon.com/outlet/CSTCFFN2PR-Costa%20Coffee/",
"https://food.noon.com/outlet/HMMSBRU44V-Hummus%20Brothers/",
"https://food.noon.com/outlet/BBBKWRP3NA-Boba%20Bae/",
"https://food.noon.com/outlet/THRDVN1JZM-The%20Red%20Oven/",
"https://food.noon.com/outlet/SBWYJG5AST-Subway/",
"https://food.noon.com/outlet/PNRS4Z8NCO-Apni%20Rasoi%20-%20Burj%20Al%20Falak/",
"https://food.noon.com/outlet/SLKRRSGHQL-Salkara%20-%20Al%20Ittihad%20Road/",
"https://food.noon.com/outlet/BRCDCFNTJH-Barcode/",
"https://food.noon.com/outlet/MMDKNT7LW1-Mamadou%20Konate%20Bakery/",
"https://food.noon.com/outlet/SHBBLK04RL-Shabab%20Al%20Khan-%20Muwaileh/",
"https://food.noon.com/outlet/07CFF0OQT3-07%20Cafe/",
"https://food.noon.com/outlet/PSTDLLCXJR-Pasta%20Della%20Nonna/",
"https://food.noon.com/outlet/JBRNRS2CMX-Jubran/",
"https://food.noon.com/outlet/PLSLDS2REY-PAUL%20Salads/",
"https://food.noon.com/outlet/RYLGLFIKS4-Royal%20Gulf/",
"https://food.noon.com/outlet/MNVSNR4LXE-Manvasanai/",
"https://food.noon.com/outlet/MDKVHLSVIH-Mado/",
"https://food.noon.com/outlet/MBRCFEY71F-Ombre%20Cafe/",
"https://food.noon.com/outlet/NSTRCS21L3-Nuestra%20Casa/",
"https://food.noon.com/outlet/NLRSTR5Y7T-Nila/",
"https://food.noon.com/outlet/HGHRNGMV0S-Highrange/",
"https://food.noon.com/outlet/KHFYFIWRXU-Khafayef/",
"https://food.noon.com/outlet/PKNDCPNU4X-Poke%20&%20Co%20-%20Al%20Raha/",
"https://food.noon.com/outlet/SLCFYNLD3Q-Sal%20Cafe/",
"https://food.noon.com/outlet/WRPPDHKQDG-Wrapped/",
"https://food.noon.com/outlet/LRFRPVB6HI-Al%20Rifai/",
"https://food.noon.com/outlet/GRNHSRPUYF-Green%20House/",
"https://food.noon.com/outlet/CHCFLCRJRO-Chic%20Flic%20%7C%20Fried%20Chicken%20Burgers/",
"https://food.noon.com/outlet/LBTLMLMSHG-Al%20Bait%20Al%20Malaky%20Mandi/",
"https://food.noon.com/outlet/DKKTSH7P7D-Dakkat%20Shay/",
"https://food.noon.com/outlet/MRMHW81VY3-Miramiah/",
"https://food.noon.com/outlet/GRDNFSA06K-Garden%20Of%20Spice/",
"https://food.noon.com/outlet/SMKDBNYK7M-Smoked%20Bun/",
"https://food.noon.com/outlet/SHMSNBEXLH-Shamseen%20Bakeries/",
"https://food.noon.com/outlet/WHTLMNUAYA-Wahat%20Al%20Mandi/",
"https://food.noon.com/outlet/CLB7XYW30M-Club%207/",
"https://food.noon.com/outlet/TPPVPPPQNO-Topi%20Vappa%20Biriyani/",
"https://food.noon.com/outlet/VLLVN49YJJ-Vallavan/",
"https://food.noon.com/outlet/CKLNDMZLCD-Cake%20Land/",
"https://food.noon.com/outlet/LYQTLF6AAN-Al%20Yaqoot%20Al%20Afghani/",
"https://food.noon.com/outlet/BRKTYL8Y5F-Barakat/",
"https://food.noon.com/outlet/LBKLMNG02E-ALBAIK%20-%20Al%20Manar%20Mall/",
"https://food.noon.com/outlet/MHFLHYC7II-Mahfil%20Hyderabad/",
"https://food.noon.com/outlet/LTSV5MD992-Let's%20Avo!/",
"https://food.noon.com/outlet/CHCLPRUTZZ-Chocola%20Pure/",
"https://food.noon.com/outlet/KSHRN3QCIY-Kosharina/",
"https://food.noon.com/outlet/GFRKSTXBLJ-Gafoorka's%20Thattukada/",
"https://food.noon.com/outlet/GDVCHCVYK5-Godiva%20Caf%C3%A9/",
"https://food.noon.com/outlet/PPPRTZPYXC-PappaRoti/",
"https://food.noon.com/outlet/KRSHBR3JY6-Krush%20Burger/",
"https://food.noon.com/outlet/HLTHYFJHBA-Healthy%20Farm%20Eatery/",
"https://food.noon.com/outlet/LSTSND1JMJ-Last%20Sandwich/",
"https://food.noon.com/outlet/DSTSTRK8TA-Desi%20Taste/",
"https://food.noon.com/outlet/GDVRNDMF1T-Godavari%20Andhra/",
"https://food.noon.com/outlet/PRTNFL9W5C-Operation%20Falafel/",
"https://food.noon.com/outlet/BNFRMCCJE0-Bean%20Farm%20Cafe/",
"https://food.noon.com/outlet/MYLSMR4K7N-Meylas%20Emirati/",
"https://food.noon.com/outlet/KSHRYBMPB8-Koshary%20Abu%20Tarek/",
"https://food.noon.com/outlet/NWGRNDNTYN-New%20Grand/",
"https://food.noon.com/outlet/GLDNCRU2EJ-Golden%20Crust/",
"https://food.noon.com/outlet/PNJBFLWP24-Punjab%20Flower/",
"https://food.noon.com/outlet/PPJHNSMVH6-Papa%20Johns/",
"https://food.noon.com/outlet/KWBKRYZ499-Kawaii%20Japanese%20Bakery/",
"https://food.noon.com/outlet/LMRRSTMD5T-Mama%20Egypt/",
"https://food.noon.com/outlet/CHRLYS7EDX-Charleys%20Philly%20Steaks/",
"https://food.noon.com/outlet/TJMHLJHZBO-Taj%20Mahal/",
"https://food.noon.com/outlet/LHDBTCOR32-Al%20Huda%20Butchery/",
"https://food.noon.com/outlet/BSTBBJSWSQ-Latea/",
"https://food.noon.com/outlet/PNDHTP6QW0-Panda%20Hot%20Pot/",
"https://food.noon.com/outlet/BMBYBNRB3L-Bombay%20Bungalow/",
"https://food.noon.com/outlet/FRSSWTN8R2-Feras%20Sweets/",
"https://food.noon.com/outlet/TKTKRSGGEH-Tuk%20Tuk/",
"https://food.noon.com/outlet/SN5RSTFIML-Asian%205/",
"https://food.noon.com/outlet/CHCKNG3IB5-ChicKing%20-%20Al%20Nahdha/",
"https://food.noon.com/outlet/THSCFQDT9Z-T%20House%20Cafe/",
"https://food.noon.com/outlet/NDLRMXSWS5-Noodle%20Room%20Express/",
"https://food.noon.com/outlet/BKRBYMKD8Z-Bakeria%20by%20Emarat/",
"https://food.noon.com/outlet/CLCTGR8ULL-Calicut%20Grill/",
"https://food.noon.com/outlet/GRMNDNYZT2-German%20Doner%20Kebab%20-%20Al%20Muneera/",
"https://food.noon.com/outlet/JD07VU5S4V-Jade/",
"https://food.noon.com/outlet/KLSHPRBXZY-Kailash%20Parbat%20-%20Yas%20Island/",
"https://food.noon.com/outlet/HYDRBDGN2N-Hyderabad/",
"https://food.noon.com/outlet/VTNMSPNNKV-Vietnamese%20Pho/",
"https://food.noon.com/outlet/BRGRCD055H-Burger%20&%20Co/",
"https://food.noon.com/outlet/CLDSTNX8ET-Cold%20Stone%20Creamery/",
"https://food.noon.com/outlet/BRZTIULMQ1-Birzeit/",
"https://food.noon.com/outlet/LFNRRSV5LA-Al%20Fanar/",
"https://food.noon.com/outlet/NNDSHBGD9D-Nando's/",
"https://food.noon.com/outlet/BGBTS7GB0H-Big%20Bites%20Pinoy%20Restaurant/",
"https://food.noon.com/outlet/KPPCHCJOIG-Kpop%20Chicken/",
"https://food.noon.com/outlet/KRSRMT6WDS-Kaara%20Saaram/",
"https://food.noon.com/outlet/LMHFLRNIU5-Al%20Mehfal/",
"https://food.noon.com/outlet/TXSRDHM2GZ-Texas%20Roadhouse/",
"https://food.noon.com/outlet/MTTHCHS4VF-Meet%20The%20Cheese/",
"https://food.noon.com/outlet/BKLRBZ2QL7-Bake%20Al%20Arab/",
"https://food.noon.com/outlet/TPVPPBNX3Z-Topi%20Vappa%20Biryani/",
"https://food.noon.com/outlet/LBKSHRHK91-ALBAIK%20-%20Sharjah%20City%20Center/",
"https://food.noon.com/outlet/NDWST8NH3T-Nad%20Wasit/",
"https://food.noon.com/outlet/FRNLRHKT2G-Fern%20El%20Raihan/",
"https://food.noon.com/outlet/GNSDL8UBVY-Gino's%20Deli/",
"https://food.noon.com/outlet/RKNLSHWUB4-RUKN%20ALSHAI%20W%20ALSMBOSA%20CAFETERIA/",
"https://food.noon.com/outlet/FLPNFSJ8PQ-Filipino%20Fiesta/",
"https://food.noon.com/outlet/CHCKNC04DU-Chick'n%20Co/",
"https://food.noon.com/outlet/FRZ83EJIGM-Freez/",
"https://food.noon.com/outlet/MTMHLDL7UL-Motimahal%20Delux/",
"https://food.noon.com/outlet/LJHCFTTXYZ-Al%20Jah%20Cafeteria/",
"https://food.noon.com/outlet/BTMBDLLHHE-Bait%20Um%20Abdallah/",
"https://food.noon.com/outlet/PPSPZZDPEP-Papas%20Pizza/",
"https://food.noon.com/outlet/RZBLBNF1L3-Roz%20Blaban%20Dairy/",
"https://food.noon.com/outlet/PL09V6HZNM-PAUL%20Bakery%20&%20Restaurant/",
"https://food.noon.com/outlet/LLH5AS9TDJ-Leila/",
"https://food.noon.com/outlet/MRSHAJMDQU-Maroosh/",
"https://food.noon.com/outlet/BKRST98P98-Bakerist/",
"https://food.noon.com/outlet/BNFDRY0WJV-Bonfood%20Royal/",
"https://food.noon.com/outlet/HMLLRSUIYA-Hamlol/",
"https://food.noon.com/outlet/PH7VTNOMS9-Pho%207%20Vietnamese/",
"https://food.noon.com/outlet/TSNDCV8MX8-Eats%20&%20%20Co%20-%20Al%20Raha/",
"https://food.noon.com/outlet/JNGLJC1H98-Jungle%20Juice/",
"https://food.noon.com/outlet/DLBRSVAZP6-Deli%20Bros/",
"https://food.noon.com/outlet/KKMCPMPEET-Akko/",
"https://food.noon.com/outlet/BRKFSTL96Y-Breakfast%20to%20Breakfast%201990/",
"https://food.noon.com/outlet/CHYHBHE10P-Chay%20Hub/",
"https://food.noon.com/outlet/LRZTMTGSRH-Al%20Arz%20Automatic%20Bakery/",
"https://food.noon.com/outlet/DVSHTC83AX-Dave's%20Hot%20Chicken/",
"https://food.noon.com/outlet/KRZPC22K7V-Karaz/",
"https://food.noon.com/outlet/STGTIU57NB-Eastgate/",
"https://food.noon.com/outlet/CHCMLTFUN4-Chocomelt/",
"https://food.noon.com/outlet/MMRYMPOM6G-Omi%20Maryam/",
"https://food.noon.com/outlet/NMSTNDV1T1-Namaste%20India/",
"https://food.noon.com/outlet/KNWNNDWV8D-Kanawana%20Indian/",
"https://food.noon.com/outlet/VSNTBHTFI6-Vasanta%20Bhavan/",
"https://food.noon.com/outlet/TCSBRRT4PU-Tacos%20&%20Burritos/",
"https://food.noon.com/outlet/BNFT43NAVJ-Bon%20Fete/",
"https://food.noon.com/outlet/LHLLTR2B9Z-Al%20Helal%20Traditional%20Kitchen/",
"https://food.noon.com/outlet/STCKMGH0F3-Stick%20Magic%20Mandi/",
"https://food.noon.com/outlet/RYLSWTTK77-Royal%20Sweets/",
"https://food.noon.com/outlet/RPRMXPVQXK-Rupee%20Room%20Express/",
"https://food.noon.com/outlet/FNCFRSPAMU-Fen%20Caf%C3%A9/",
"https://food.noon.com/outlet/BRYNJNPS46-Biryani%20Junction/",
"https://food.noon.com/outlet/THBHKKBYKR-Bhukkad%20Cafe/",
"https://food.noon.com/outlet/LBKLMJGWEZ-ALBAIK%20-%20Al%20Majaz/",
"https://food.noon.com/outlet/NLLSRS88U5-Nells/",
"https://food.noon.com/outlet/PZZDRCEPT8-Pizza%20Di%20Rocco/",

        # Add more here...
    ]

    output_file = "output.json"
    failed_file = "failed.json"

    scraped_data = load_json(output_file)
    failed_urls = load_json(failed_file)
    scraped_urls = {entry["url"] for entry in scraped_data}

    for url in urls:
        if url in scraped_urls:
            print(f"â­ï¸ Already scraped: {url}")
            continue

        result = scrape_restaurant(url)
        if result:
            scraped_data.append(result)
            save_json(scraped_data, output_file)
        else:
            failed_urls.append(url)
            save_json(failed_urls, failed_file)

        time.sleep(1.5)  # Slight delay to reduce chances of block

if __name__ == "__main__":
    main()

