-- ================================================================
-- Talabat UAE — pgAdmin4 Query Reference
-- Generated by export_excel_review.py
-- ================================================================


-- Q1: Unique menu items with one representative restaurant
--     355,727 rows — use this for std_term review in Excel
-- ----------------------------------------------------------------
SELECT DISTINCT ON (mi.item_key_clean)
    r.branch_id, r.restaurant_id, r.restaurant_name, r.ld_name, r.map_url,
    array_to_string(r.serves_cuisine, ', ')    AS serves_cuisines,
    r.ld_lat, r.ld_lon, r.area_id, r.area_name,
    mi.item_key_clean,
    replace(mi.item_key_clean, '_', ' ')       AS item_name_readable,
    mi.menu_category_clean,
    mi.description_clean,
    mi.std_term, mi.taxonomy,
    ROUND(mi.confidence::numeric, 4)           AS confidence,
    mi.method, mi.review_required
FROM talabat_menu_items mi
INNER JOIN talabat_restaurants r ON mi.branch_id = r.branch_id
WHERE mi.item_key_clean IS NOT NULL
ORDER BY mi.item_key_clean, r.restaurant_name;


-- Q2: Full 1.1M join (too large for Excel — use for CSV/data tools)
--     Run with COPY for CSV: COPY (SELECT ...) TO '/path/output.csv' CSV HEADER;
-- ----------------------------------------------------------------
SELECT
    r.branch_id, r.restaurant_id, r.restaurant_name,
    array_to_string(r.serves_cuisine, ', ')  AS serves_cuisines,
    r.area_name,
    mi.item_key_clean,
    replace(mi.item_key_clean, '_', ' ')     AS item_name_readable,
    mi.menu_category_clean, mi.description_clean,
    mi.std_term, mi.taxonomy,
    ROUND(mi.confidence::numeric, 4)         AS confidence,
    mi.method, mi.review_required
FROM talabat_menu_items mi
INNER JOIN talabat_restaurants r ON mi.branch_id = r.branch_id
ORDER BY r.area_name, r.restaurant_name, mi.menu_category_clean;


-- Q3: Full join filtered by AREA (manageable Excel slices ~50K-350K rows)
--     Change the area_name value as needed. List of areas below:
--     'Al Barsha 3', 'Al Dhagaya', 'Zayed Sports City', 'Al Jaddaf',
--     'Al Barsha 1', 'Al Barsha South', 'Al Garhoud', 'Al Furjan'
-- ----------------------------------------------------------------
SELECT
    r.branch_id, r.restaurant_id, r.restaurant_name, r.area_name,
    mi.item_key_clean,
    replace(mi.item_key_clean, '_', ' ')  AS item_name_readable,
    mi.menu_category_clean,
    mi.std_term, mi.taxonomy,
    ROUND(mi.confidence::numeric, 4)      AS confidence,
    mi.method, mi.review_required
FROM talabat_menu_items mi
INNER JOIN talabat_restaurants r ON mi.branch_id = r.branch_id
WHERE r.area_name = 'Al Barsha 3'          -- << change area here
ORDER BY r.restaurant_name, mi.menu_category_clean, mi.item_key_clean;


-- Q4: Only review_required items — unique, worst confidence first
-- ----------------------------------------------------------------
SELECT DISTINCT ON (mi.item_key_clean)
    r.restaurant_name, r.area_name,
    mi.item_key_clean,
    replace(mi.item_key_clean, '_', ' ')  AS item_name_readable,
    mi.menu_category_clean,
    mi.std_term, mi.taxonomy,
    ROUND(mi.confidence::numeric, 4)      AS confidence,
    mi.method
FROM talabat_menu_items mi
INNER JOIN talabat_restaurants r ON mi.branch_id = r.branch_id
WHERE mi.review_required = TRUE
  AND mi.item_key_clean IS NOT NULL
ORDER BY mi.item_key_clean, mi.confidence;


-- Q5: Coverage summary (single row)
-- ----------------------------------------------------------------
SELECT
    COUNT(*)                                           AS total_items,
    COUNT(std_term)                                    AS matched,
    COUNT(DISTINCT item_key_clean)                     AS unique_keys,
    COUNT(*) FILTER (WHERE method='rule')              AS by_rule,
    COUNT(*) FILTER (WHERE method='exact')             AS by_exact,
    COUNT(*) FILTER (WHERE method='fuzzy')             AS by_fuzzy,
    COUNT(*) FILTER (WHERE method='tfidf')             AS by_tfidf,
    COUNT(*) FILTER (WHERE method='embedding')         AS by_embedding,
    COUNT(*) FILTER (WHERE method='manual')            AS by_manual,
    COUNT(*) FILTER (WHERE review_required=TRUE)       AS needs_review
FROM talabat_menu_items;


-- Q6: Per-restaurant classification coverage
-- ----------------------------------------------------------------
SELECT
    r.branch_id, r.restaurant_name, r.area_name,
    COUNT(mi.id)                                       AS total_items,
    COUNT(mi.std_term)                                 AS classified,
    COUNT(*) FILTER (WHERE mi.review_required=TRUE)    AS needs_review,
    ROUND(100.0 * COUNT(mi.std_term)
          / NULLIF(COUNT(mi.id), 0), 1)                AS coverage_pct
FROM talabat_restaurants r
LEFT JOIN talabat_menu_items mi ON mi.branch_id = r.branch_id
GROUP BY r.branch_id, r.restaurant_name, r.area_name
ORDER BY total_items DESC;


-- Q7: All restaurants reference
-- ----------------------------------------------------------------
SELECT
    branch_id, restaurant_id, restaurant_name, ld_name, map_url,
    array_to_string(serves_cuisine, ', ')  AS serves_cuisines,
    array_to_string(key_cuisines,   ', ')  AS key_cuisines,
    restaurant_type, outlet_type,
    ld_lat, ld_lon, area_id, area_name,
    first_scraped_at, updated_at
FROM talabat_restaurants
ORDER BY area_name, restaurant_name;
